#!/usr/bin/env python3
"""Complete ALL remaining grammar summaries."""
import json,os

ROOT=os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(ROOT,'data','modules.json'),'r',encoding='utf-8') as f:
    modules=json.load(f)

G={
    # ============ 代词续 ============
    'pronoun-demonstrative':{'rules':['指示代词 this/these（近指）和 that/those（远指）','this/that 指单数，these/those 指复数','电话用语：This is...（我是...）；Who is that?（你是谁？）','that/those 可代替前面提到的名词避免重复：The weather in Beijing is colder than that in Shanghai'],'examples':['This is my book and that is yours.','The cars made in Japan are better than those made in China.'],'common_mistakes':['this are → this is','that 代替不可数/单数，those 代替复数']},
    'pronoun-it':{'rules':['it 作代词指代上文提到的事物：I have a dog. It is very cute.','it 作无人称主语：表天气(It is raining)、时间(It is late)、距离(It is far)','it 作形式主语：It is important to learn English.','it 作形式宾语：I find it difficult to understand.','强调句型：It is/was...that/who...'],'examples':['It is never too late to learn.','I think it necessary to tell him the truth.','It was Tom who broke the window.'],'common_mistakes':['用 this/that 代替 it 作形式主语','强调句中误用 which 代替 that']},

    # ============ 数词续 ============
    'numeral-time-date':{'rules':['年份读法：1998→nineteen ninety-eight；2000→two thousand','日期写法：June 1st/June 1/1st June；读法：June the first','时刻表达：整点→...o\'clock；半点→half past...；分钟→...past/to','in one\'s twenties/thirties=在某人20/30多岁时'],'examples':['He was born on January 27, 1998.','She is in her early twenties.'],'common_mistakes':['on 1998 → in 1998（年份用 in）','in Monday → on Monday（具体某天用 on）']},
    'numeral-approximate':{'rules':['约数表达：about/around/approximately + 数字','hundreds/thousands/millions of = 成百上千','dozens of = 几十；scores of = 许多','several + 名词 = 几个','some + 数字 = 大约：some fifty people = 大约50人'],'examples':['Hundreds of people attended the concert.','There are dozens of books on the shelf.'],'common_mistakes':['two hundreds → two hundred（具体数字不加s）','hundred of → hundreds of（表约数加s和of）']},

    # ============ 冠词续 ============
    'article-fixed':{'rules':['固定短语中冠词不可省略：in the morning, at the moment, all the time','the + 比较级, the + 比较级 = 越...越...','at the same time, on the other hand, in the end, by the way','have a cold, have a fever, have a headache（疾病前用 a）','make a decision, take a walk, have a look（固定搭配中 a）'],'examples':['The more you read, the more you know.','He is in the habit of getting up early.'],'common_mistakes':['in morning → in the morning','at same time → at the same time']},
    'article-special':{'rules':['序数词前加 a 表示"又一"：a second chance','most 前不加 the 表示"大多数"：most people','抽象名词具体化时可加 a：a success（一个成功的人/事）, a pleasure（一件乐事）','物质名词具体化：a coffee（一杯咖啡）, a beer（一杯啤酒）'],'examples':['He tried a second time and succeeded.','Most students like sports.'],'common_mistakes':['most of students → most students（泛指不加 the）','a second 和 the second 混淆']},

    # ============ 形容词续 ============
    'adj-functions':{'rules':['形容词作定语修饰名词：a beautiful girl','形容词作表语（系动词后）：She looks happy.','常见的系动词：be, become, get, turn, grow, look, sound, smell, taste, feel, seem, appear, keep, stay','形容词作宾语补足语：make me happy, find it interesting','多个形容词排列顺序：限定词→观点→大小→形状→年龄→颜色→来源→材料→用途+名词'],'examples':['The food tastes delicious.','We found the movie very interesting.'],'common_mistakes':['She looks happily → She looks happy（系动词+形容词）','用副词修饰系动词：feel badly → feel bad']},
    'adj-order':{'rules':['多个形容词修饰名词时的排列口诀：美小圆旧黄，法国木书房','完整顺序：限定词(a/the/my)→观点(beautiful)→大小(big)→形状(round)→新旧(old)→颜色(red)→来源(Chinese)→材料(wooden)→用途(writing)+名词','同类形容词用逗号分开，不同类不用逗号'],'examples':['a beautiful big round old red Chinese wooden writing table','She has a lovely small white dog.'],'common_mistakes':['a red big apple → a big red apple（大小在颜色前）']},
    'adj-confusing':{'rules':['-ing 形容词修饰物，表示"令人...的"：interesting, exciting, boring, surprising','-ed 形容词修饰人，表示"感到...的"：interested, excited, bored, surprised','常见易混对：interesting/interested, exciting/excited, boring/bored, surprising/surprised, tiring/tired, frightening/frightened, pleasing/pleased, worrying/worried, amazing/amazed, disappointing/disappointed','以 -ly 结尾但实际是形容词：friendly, lovely, lively, lonely, likely, ugly, silly, elderly'],'examples':['The movie is interesting. I am interested in it.','She gave me a friendly smile.'],'common_mistakes':['I am interesting → I am interested（人用-ed）','She sings lovely → She sings beautifully（lovely是形容词）']},

    # ============ 副词 ============
    'adv-formation':{'rules':['副词通常由形容词加 -ly 构成：quick→quickly, careful→carefully','以辅音+y 结尾变 y 为 i+ly：happy→happily, easy→easily','以 le 结尾去 e 加 y：simple→simply, gentle→gently','以 ic 结尾加 ally：basic→basically, scientific→scientifically','有些词本身既是形容词又是副词：fast, hard, early, late, high, low, deep, near','注意：hard(努力)≠hardly(几乎不)；late(晚)≠lately(最近)；near(近)≠nearly(几乎)'],'examples':['She sings beautifully.','He works hard every day.'],'common_mistakes':['She sings beautiful → She sings beautifully','He works hardly → He works hard（hardly=几乎不）']},
    'adv-comparative':{'rules':['副词比较级和最高级的构成：单音节加 er/est（fast→faster→fastest），多音节前加 more/most（quickly→more quickly→most quickly）','不规则变化：well→better→best, badly→worse→worst, much→more→most, little→less→least, far→farther/further→farthest/furthest','比较级+than，最高级+范围。副词最高级前的 the 可省略'],'examples':['He runs faster than me.','She sings (the) best of all.'],'common_mistakes':['more faster → faster（不能用 more+er）']},
    'adv-frequency':{'rules':['频度副词表示动作发生的频率：always(100%)、usually(90%)、often(70%)、sometimes(50%)、seldom(20%)、rarely(10%)、never(0%)','频度副词位置：be 动词后、实义动词前、助动词和实义动词之间','how often 提问频率'],'examples':['He is always late.','She never eats meat.','How often do you exercise?'],'common_mistakes':['He goes always → He always goes（实义动词前）','He never is late → He is never late（be 动词后）']},
    'adv-confusing':{'rules':['hard（努力地）/ hardly（几乎不）：He works hard. / He hardly works.','late（晚）/ lately（最近）：He came late. / Have you seen him lately?','near（近）/ nearly（几乎）：He lives near. / He nearly fell.','high（高）/ highly（高度地/非常）：fly high / think highly of','deep（深）/ deeply（深深地）：dig deep / deeply moved','close（近）/ closely（仔细地）：come close / watch closely','wide（宽）/ widely（广泛地）：open wide / widely used','free（免费）/ freely（自由地）：get in free / speak freely'],'examples':['He hardly ever goes out.（他几乎不出门）','The book is widely read.（这本书被广泛阅读）'],'common_mistakes':['I can\'t hardly → I can hardly（hardly 本身已是否定）']},
    'adv-position':{'rules':['副词在句中的位置：①方式副词通常在动词后或宾语后；②地点副词在方式副词后、时间副词前；③频度副词在 be 后实义前；④句子副词（fortunately, honestly）通常在句首','多个副词顺序：方式→地点→时间'],'examples':['She sang beautifully at the concert last night.','Fortunately, no one was hurt.'],'common_mistakes':['次序错误：last night at the concert → at the concert last night']},
    'adv-negation':{'rules':['否定副词：hardly, scarcely, barely, seldom, rarely, never, little, not','否定副词置于句首时，句子要用部分倒装：Never have I seen such a beautiful sunset.','hardly...when / no sooner...than / scarcely...when = 一...就...','部分否定：not always, not completely, not all'],'examples':['Seldom does he go to the cinema.','Hardly had he arrived when it began to rain.'],'common_mistakes':['Hardly he had → Hardly had he（倒装）','I haven\'t never → I have never（双重否定错误）']},

    # ============ 介词 ============
    'prep-time':{'rules':['at + 时刻/正午/夜：at 7:00, at noon, at night, at midnight','on + 具体日期/星期/节日的某天：on Monday, on June 1st, on Christmas Day','in + 月份/季节/年/世纪：in May, in summer, in 2020, in the 21st century','in + 时间段（将来时）：in two days（两天后）','for + 时间段（持续多久）：for two hours','since + 时间点（自从）：since 2010','during + 时间段（在...期间）：during the summer','from...to... = 从...到...','by + 时间 = 到...为止：by the end of'],'examples':['We have lived here since 2015.','He will be back in an hour.'],'common_mistakes':['on May → in May（月份用 in）','in Sunday → on Sunday（星期用 on）','since two years → for two years（since+时间点）']},
    'prep-place':{'rules':['at + 小地点/点：at the door, at the bus stop, at school','in + 大地点/空间：in Beijing, in the room, in the park','on + 表面/线：on the desk, on the wall, on the river','above/over 在...上方；below/under 在...下方','between 两者之间；among 三者及以上之间','in front of 在...前面（外部）；in the front of 在...前部（内部）','behind 在...后面；beside/next to 在...旁边；near 在...附近；opposite 在...对面'],'examples':['There is a picture on the wall.','He is standing between Tom and Jerry.'],'common_mistakes':['arrive at London → arrive in London（大城市用 in）','between three → among three（三者用 among）']},
    'prep-phrases':{'rules':['介词短语 = 介词 + 名词/代词/动名词，在句中作定语、状语或表语','常见动词+介词搭配：agree with, belong to, listen to, wait for, look at/for/after, depend on, think about, care about, talk about, hear from, arrive at/in, pay for, search for, laugh at','常见形容词+介词搭配：good at, interested in, proud of, afraid of, full of, tired of, satisfied with, pleased with, angry with, busy with, different from, absent from, famous for, ready for, thankful to, kind to','常见名词+介词搭配：reason for, answer to, key to, solution to, influence on'],'examples':['He is good at playing chess.','I am looking forward to hearing from you.'],'common_mistakes':['agree sb → agree with sb','belong to sb ✅，be belonged to ❌']},
    'prep-movement':{'rules':['across 横穿（从表面穿过）：walk across the street','through 穿过（从内部穿过）：walk through the forest','along 沿着：walk along the river','toward(s) 朝向：walk toward the door','into 进入：jump into the water','onto 到...上面：climb onto the roof','out of 从...出来：get out of the car','from...to... 从...到...：from London to Paris'],'examples':['The train goes through the tunnel.','He jumped into the pool.'],'common_mistakes':['across the forest → through the forest（内部穿过用 through）']},
    'prep-common-errors':{'rules':['besides = 除了...（包括在内）= in addition to；except = 除了...（不包括在内）','except 和 besides 的区别是高频考点','between vs among：between 两者，among 三者及以上','like vs as：like + 名词（像...一样）；as + 从句（像/作为）','with vs by：with+工具（with a pen）；by+方式（by bus）','in vs after：in+时间段（将来时）；after+时间段（过去时）','on the tree（树上长的）vs in the tree（外来物在树上）'],'examples':['Besides English, he also speaks French.','All went except Tom.'],'common_mistakes':['besides 和 except 混淆','arrive to → arrive at/in']},

    # ============ 连词 ============
    'conj-coordinating':{'rules':['并列连词连接两个对等的语法成分。常见：and, or, but, so, for, yet, nor','and = 和/然后（并列/顺承）：He came in and sat down.','or = 或者/否则（选择）：Hurry up, or you\'ll be late.','but = 但是（转折）：He is old but strong.','so = 因此/所以（因果）：It rained, so we stayed home.','重要规则：because 和 so 不能同时使用；although 和 but 不能同时使用——这是中英文表达的重大区别'],'examples':['Study hard, and you will succeed.','He is rich, but he is not happy.'],'common_mistakes':['Although he is poor, but he is happy.→ Although he is poor, he is happy.（去掉 but）']},
    'conj-correlative':{'rules':['关联连词成对使用：both...and, either...or, neither...nor, not only...but also, whether...or','both...and + 复数谓语','either...or / neither...nor 遵循就近原则','not only...but also 遵循就近原则；not only 在句首时需倒装','whether...or = 无论...还是...'],'examples':['Both Tom and Mary are students.','Not only does he sing, but he also dances.'],'common_mistakes':['Both Tom and Mary is → Both Tom and Mary are','Neither he nor I are → Neither he nor I am（就近I）']},
    'conj-subordinating':{'rules':['从属连词引导状语从句或名词性从句。','原因：because（语气最强）, since, as（既然/由于）','让步：although, though（虽然）, even though（即使）, while（然而）','条件：if（如果）, unless（除非/如果不）, as long as（只要）','时间：when, while（当...时）, as（一边...一边）, before, after, since, until/till, as soon as（一...就）','目的：so that, in order that（以便）','结果：so...that, such...that（如此...以至于）','比较：than, as...as, not so/as...as'],'examples':['He didn\'t come because he was ill.','You won\'t pass unless you study hard.'],'common_mistakes':['because...so 连用','although...but 连用','until 和 not...until 混淆']},
    'conj-time':{'rules':['时间状语从句的时态规则：主将从现——主句用将来时，从句用一般现在时表将来','when = 当...时（可接短暂/持续动作）：When he comes, I will tell him.','while = 在...期间（接持续动作，常用进行时）：While I was reading, he came in.','as = 一边...一边/随着：As time goes by, we grow older.','as soon as = 一...就...：I will call you as soon as I arrive.','until/till = 直到...：not...until = 直到...才','since = 自从（主句用现在完成时）','before/after = 在...之前/后'],'examples':['I will wait until he comes back.','He has changed a lot since he moved here.'],'common_mistakes':['When he will come → When he comes（从句不用将来时）','He didn\'t come until I leave → I left（时态一致）']},
    'conj-transition':{'rules':['连接副词表示句子间的逻辑关系：however（然而）, therefore（因此）, moreover/furthermore（此外）, besides（除此之外）, otherwise（否则）, nevertheless（尽管如此）, consequently（因此）, thus（因此）, hence（因此）','连接副词不是连词，不能直接连接两个句子。需要分号或句号隔开，后面加逗号'],'examples':['He was tired; however, he kept working.','It was late. Therefore, we went home.'],'common_mistakes':['He was tired, however he kept working → He was tired; however, he kept working.（逗号连接错误）']},

    # ============ 动词 ============
    'verb-present':{'rules':['一般现在时：表示习惯性动作、客观真理、现状','形式：主语为第三人称单数时动词加 s/es；其他人称用原形','第三人称单数变化：①一般加 s；②s/x/sh/ch/o 结尾加 es；③辅音+y 变 i 加 es','标志词：every day, usually, often, always, sometimes, never','客观真理永远用一般现在时：The earth goes round the sun.'],'examples':['She goes to school by bus every day.','Light travels faster than sound.'],'common_mistakes':['She go → She goes（三单加s）','He doesn\'t goes → He doesn\'t go（doesn\'t后原形）']},
    'verb-past':{'rules':['一般过去时：表示过去发生的动作或状态','规则变化：动词+ed（以e结尾+d；辅音+y变i+ed；重读闭音节双写+ed）','不规则变化需要单独记忆：go→went, come→came, see→saw, take→took, get→got, make→made, have→had, do→did, say→said, tell→told','标志词：yesterday, last night/week/month/year, ...ago, just now, in 1990, the other day'],'examples':['I saw a great movie last night.','He came to China in 2010.'],'common_mistakes':['I see him yesterday → I saw him yesterday','He didn\'t went → He didn\'t go（did 后原形）']},
    'verb-future':{'rules':['一般将来时：will/shall + 动词原形','be going to + 动词原形 = 打算做/即将发生','标志词：tomorrow, next week/month/year, in the future, soon, later','时间/条件状语从句中用一般现在时表将来（主将从现）','过去将来时：would + 动词原形（用于宾语从句中，主句为过去时）'],'examples':['They will arrive tomorrow.','He said he would come the next day.'],'common_mistakes':['He will comes → He will come（will 后原形）','If it will rain → If it rains（从句用现在时）']},
    'verb-present-perfect':{'rules':['现在完成时：have/has + 过去分词','用法：①过去动作对现在的影响；②从过去持续到现在的动作/状态','标志词：since+时间点, for+时间段, already, yet, ever, never, just, recently, so far, up to now, in the past few years','have been to（去过已回）, have gone to（去了未回）, have been in（待在某地）'],'examples':['She has lived here since 2010.','I have already finished my homework.'],'common_mistakes':['I have gone to Beijing → I have been to Beijing（已回）','for 和 since 混淆']},
    'verb-past-perfect':{'rules':['过去完成时：had + 过去分词（过去的过去）','用于表示在过去某个时间或动作之前已经完成的动作','标志词：by the end of last..., by the time + 过去时, before + 过去时','常用于宾语从句中，主句为过去时，从句动作发生在主句动作之前','hardly/scarcely...when；no sooner...than 句型中主句用过去完成时'],'examples':['By the end of last month, we had learned 2000 words.','He had left before I arrived.'],'common_mistakes':['混淆现在完成时和过去完成时','had 后不用过去式：had went → had gone']},
    'verb-progressive':{'rules':['进行时态：be + 现在分词（-ing）','现在进行时：am/is/are + doing——表示此刻正在进行的动作','过去进行时：was/were + doing——表示过去某时刻正在进行的动作','标志词：now, right now, at the moment, Look!, Listen!','while 从句常用过去进行时','现在分词变化：①一般+ing；②不发音e结尾去e+ing；③重读闭音节双写+ing；④ie变y+ing'],'examples':['Look! The birds are flying in the sky.','While I was cooking, the phone rang.'],'common_mistakes':['He is run → He is running（双写n）','表状态和心理的动词不用进行时：know, want, like, believe']},
    'verb-passive':{'rules':['被动语态：be + 过去分词','各种时态的被动：一般现在→am/is/are+done；一般过去→was/were+done；一般将来→will be+done；现在完成→have/has been+done；情态动词→can/must be+done','被动语态的使用：不知道/不必知道动作执行者；强调动作承受者','主动变被动：宾语变主语，谓语变 be+done，主语变 by+宾语','感官动词/使役动词在被动中要还原 to：make sb do → sb be made to do'],'examples':['English is spoken all over the world.','The window was broken by Tom.'],'common_mistakes':['The cake was made by my mother yesterday ✅','He was made work → He was made to work（被动还原 to）']},
    'verb-modal':{'rules':['情态动词后接动词原形，无人称和数的变化','can/could = 能够/可以（能力/允许）','may/might = 可以/可能（允许/推测）','must = 必须/一定（义务/强制/推测）。mustn\'t = 禁止/不准','should/ought to = 应该（建议/义务）','need = 需要（情态动词用法：need do；实义动词：need to do）。needn\'t = 不必','will/would = 将/愿意。would 也用于委婉请求','had better + 原形 = 最好做。否定：had better not do','used to do = 过去常常。be used to doing = 习惯做'],'examples':['You mustn\'t smoke here.','He used to live in London.','Must I go? No, you needn\'t.'],'common_mistakes':['mustn\'t = 禁止(不是"不必")','had better to do → had better do','used to do 和 be used to doing 混淆']},
    'verb-agreement':{'rules':['主谓一致核心规则：谓语动词在数和人称上与主语保持一致','就近原则：either...or, neither...nor, not only...but also, there be','意义一致：集合名词、学科名称、时间距离金钱','语法一致：不定式/动名词/主语从句→单数','many a + 单数名词 → 单数','a number of + 复数名词 → 复数（=many）','the number of + 复数名词 → 单数（...的数量）','more than one + 单数名词 → 单数'],'examples':['Neither he nor I am wrong.','A number of students are absent today.','The number of students is 50.'],'common_mistakes':['A number of... is → are','The number of... are → is']},
    'verb-phrasal':{'rules':['动词短语 = 动词 + 介词/副词，构成新的含义','常见动词短语：look for(寻找), look after(照顾), look up(查阅), look forward to(期待)；turn on(打开), turn off(关闭), turn up(调高), turn down(调低/拒绝)；take off(起飞/脱下), take up(开始从事), take care of(照顾)；put on(穿上), put off(推迟), put up(张贴)；give up(放弃), give in(屈服), give away(赠送)；get up(起床), get on(上车), get off(下车), get along with(相处)','代词宾语必须放在动词和副词之间：turn it on ✅，turn on it ❌'],'examples':['Please turn off the light. / Please turn it off.','He gave up smoking last year.'],'common_mistakes':['turn on it → turn it on（代词放中间）']},

    # ============ 非谓语动词 ============
    'inf-object':{'rules':['不定式 to do 可以作宾语。下列动词只能接不定式作宾语：want, decide, promise, agree, refuse, plan, hope, wish, expect, learn, manage, offer, prepare, pretend, afford, fail, happen, seem','疑问词 + to do：what to do, how to do it, where to go, when to start','it 作形式宾语：find/think/feel/make + it + adj + to do'],'examples':['He promised to come on time.','I don\'t know what to do next.'],'common_mistakes':['want doing → want to do','decide doing → decide to do']},
    'inf-subject-adverbial':{'rules':['不定式作主语：To learn English well is important. → 常用 It is important to learn English well.','不定式作定语：I have something to tell you. / a house to live in','不定式作状语：表目的(in order to/so as to), 表结果(too...to, enough to), 表原因','It is + adj + for/of sb to do：for 表客观情况，of 表人品特征'],'examples':['It is necessary for you to take exercise.','He is too young to go to school.'],'common_mistakes':['a pen to write → a pen to write with（介词不能省）']},
    'gerund-object':{'rules':['动名词 doing 作宾语。下列动词只能接动名词：enjoy, mind, finish, practise, keep, avoid, suggest, admit, deny, miss, imagine, consider, risk, delay, postpone, appreciate','介词 + 动名词：thank you for helping, be good at doing, be interested in doing','注意：look forward to/be used to/devote to 中的 to 是介词，后接 doing','stop/remember/forget/regret/try/mean/go on + doing vs to do 含义不同'],'examples':['I enjoy reading books.','Would you mind opening the window?'],'common_mistakes':['enjoy to do → enjoy doing','look forward to see → look forward to seeing']},
    'gerund-subject':{'rules':['动名词作主语表示一般性、习惯性的行为：Reading is my hobby.','It is no use/no good/useless/worth + doing','There is no + doing = 不可能...：There is no knowing what will happen.','动名词的复合结构：物主代词/名词所有格 + doing：His coming surprised us.'],'examples':['Swimming is good for health.','It is no use crying over spilt milk.'],'common_mistakes':['Read is my hobby → Reading is my hobby（动名词作主语）']},
    'participle-present':{'rules':['现在分词(-ing)表示主动或正在进行的动作','现在分词作定语：the sleeping baby = the baby who is sleeping','现在分词作状语：Hearing the news, he jumped with joy.','现在分词作宾补：see/hear/watch sb doing','现在分词的完成式：having done（表示发生在谓语之前）'],'examples':['The girl standing there is my sister.','Having finished his homework, he went out to play.'],'common_mistakes':['Having finished 和 Having been finished 混淆']},
    'participle-past':{'rules':['过去分词(-ed)表示被动或已完成的动作','过去分词作定语：the broken window = the window which was broken','过去分词作状语：Seen from the hill, the city looks beautiful.','过去分词作宾补：have/get sth done, make oneself understood','不规则动词的过去分词需要单独记忆'],'examples':['The book written by Lu Xun is very popular.','I had my hair cut yesterday.'],'common_mistakes':['现在分词和过去分词混淆：falling leaves(正在落的) vs fallen leaves(已落下的)']},
    'nonfinite-confusing':{'rules':['不定式 vs 动名词：1) 只能接不定式：want, decide, promise；2) 只能接动名词：enjoy, mind, finish；3) 两者均可但含义不同：stop, remember, forget, regret, try, mean','stop to do(停下来去做) vs stop doing(停止做)','remember to do(记得要做) vs remember doing(记得做过)','forget to do(忘记要做) vs forget doing(忘记做过)','regret to do(遗憾要做) vs regret doing(后悔做过)','try to do(努力做) vs try doing(尝试做)','mean to do(打算做) vs mean doing(意味着)'],'examples':['Remember to lock the door. / I remember locking the door.','He tried to open the door but failed. / He tried knocking at the back door.'],'common_mistakes':['stop to do 和 stop doing 含义混淆','forget/remember 的 to do/doing 区分']},
    'nonfinite-vs-tense':{'rules':['非谓语动词不能单独作谓语。选择哪一种非谓语形式取决于：①与逻辑主语的关系（主动/被动）；②与谓语动词的时间关系（同时/之前）','doing = 主动/同时；having done = 主动/之前；done = 被动/完成；being done = 被动/同时；having been done = 被动/之前','to do = 将来/目的；to be doing = 同时进行；to have done = 之前完成'],'examples':['Having finished his work, he went home.','The building being built now is a hospital.'],'common_mistakes':['Having finished vs Having been finished 混淆']},

    # ============ 句子结构 ============
    'sent-patterns':{'rules':['英语五大基本句型：①S+V（主谓）：Birds fly.；②S+V+O（主谓宾）：I love you.；③S+V+P（主系表）：She is happy.；④S+V+IO+DO（主谓间宾直宾）：He gave me a book.；⑤S+V+O+OC（主谓宾宾补）：We made him monitor.','简单句→并列句→复合句','陈述句、疑问句、祈使句、感叹句四种句子类型'],'examples':['She gave me a present.（S+V+IO+DO）','They painted the wall white.（S+V+O+OC）'],'common_mistakes':['缺少谓语动词','一个简单句中出现两个谓语动词']},
    'sent-there-be':{'rules':['There be 句型表示"某地存在某人/物"','be 动词与最靠近的名词保持数的一致（就近原则）','There be 的各种时态：There is/are, There was/were, There will be, There have/has been, There used to be','There be + 名词 + doing/done/to do：There is a man waiting outside.','There seems/appears/happens to be...'],'examples':['There is a book and two pens on the desk.','There used to be a cinema here.'],'common_mistakes':['There have a book → There is a book（不能用 have）','There are a book → There is a book（就近 a book）']},
    'sent-tag':{'rules':['反意疑问句 = 陈述句 + 简短问句。前肯后否，前否后肯','时态和主语要与陈述部分一致','Let\'s... → shall we?；Let us... → will you?','祈使句 → will you? / won\'t you?','I\'m... → aren\'t I?','I think/believe + 从句 → 反意与从句一致','陈述部分有否定词(never, seldom, hardly等)视为否定，反意用肯定'],'examples':['He is a student, isn\'t he?','Let\'s go, shall we?','I don\'t think he will come, will he?'],'common_mistakes':['I\'m right, amn\'t I → aren\'t I','Let\'s 和 Let us 的反意不同']},
    'sent-exclamatory':{'rules':['感叹句：What + (a/an) + 形容词 + 名词 + 主谓！；How + 形容词/副词 + 主谓！','What 修饰名词；How 修饰形容词或副词','What a nice day (it is)! = How nice a day it is!','What + 不可数名词/复数名词！：What nice weather!'],'examples':['What a beautiful flower!','How fast he runs!'],'common_mistakes':['What fast he runs → How fast he runs（副词用 How）','How a beautiful flower → What a beautiful flower（名词用 What）']},
    'sent-negation':{'rules':['否定句的构成：be/have/情态动词+not；实义动词用 don\'t/doesn\'t/didn\'t','部分否定：not all, not every, not both = 并非所有的都','双重否定 = 肯定：You can\'t not go.（你必须去）','否定转移：I don\'t think he will come. = I think he won\'t come.','半否定词：hardly, scarcely, rarely, seldom, little, few'],'examples':['I don\'t think it will rain.','Not all the students passed the exam.'],'common_mistakes':['I think he won\'t come → I don\'t think he will come（否定转移）']},
    'sent-inversion':{'rules':['完全倒装：Here/There/Now/Then/Out/In + 谓语 + 主语','部分倒装：否定词/Only+状语在句首时，主句部分倒装（助动词/情态动词+主语+动词）','常用部分倒装的情况：Never/Seldom/Hardly/Scarcely/Not only/No sooner/Not until/Only then','So/Neither/Nor + 助动词 + 主语 = ...也一样/也不','as/though 引导的让步从句：Child as he is, he knows a lot.'],'examples':['Never have I seen such a beautiful place.','Only in this way can we solve the problem.'],'common_mistakes':['Only then he realized → Only then did he realize','Hardly he had → Hardly had he']},
    'sent-emphasis':{'rules':['强调句型：It is/was + 被强调部分 + that/who + 其余','可以强调主语、宾语、状语，但不能强调谓语','强调谓语：do/does/did + 动词原形','What...is/was... 结构也可表强调'],'examples':['It was Tom who broke the window.','I do hope you can come.'],'common_mistakes':['强调时间/地点时误用 when/where 代替 that']},

    # ============ 宾语从句 ============
    'obj-that':{'rules':['that 引导的宾语从句：that 只起连接作用，在从句中不充当成分，口语中可省略','常用 that 引导宾语从句的动词：say, think, believe, know, hope, wish, suggest, find, hear, see, notice, explain, show, prove','that 从句作介词的宾语：except that, in that, but that','it 作形式宾语：I think it necessary that...','suggest/insist/order/demand + that + (should) do（虚拟语气）'],'examples':['I think (that) he is right.','He suggested that we (should) start early.'],'common_mistakes':['漏掉 that（正式文体需保留）','suggest 后的从句忘记用虚拟语气']},
    'obj-if-whether':{'rules':['whether/if 引导的宾语从句，表示"是否"','whether 和 if 的区别：①whether 可用于介词后（It depends on whether...）；②whether 可用于不定式前（I don\'t know whether to go）；③whether 可与 or not 直接连用（whether or not）；④whether 可引导主语从句（Whether he comes is uncertain）','if 不能用于以上四种情况','whether...or = 无论...还是...'],'examples':['I don\'t know whether/if he will come.','It depends on whether it rains.'],'common_mistakes':['介词后用 if 代替 whether','whether/if 引导的从句语序错误']},
    'obj-wh':{'rules':['wh- 词引导的宾语从句：what, who, whom, which, whose, where, when, why, how','关键规则：从句必须用陈述语序（主语+谓语），不能用疑问语序','比较：Do you know where he lives?（陈述语序✅）→ where does he live?（疑问语序❌）','what 在从句中作主语、宾语或表语：I don\'t know what happened.','疑问词 + to do：I don\'t know what to do.'],'examples':['Can you tell me where the post office is?','I want to know when we should start.'],'common_mistakes':['Can you tell me where is the post office? → ...where the post office is?（陈述语序）']},
    'obj-tense':{'rules':['宾语从句的时态呼应：主句为现在时→从句可用任何时态；主句为过去时→从句必须用相应的过去时','客观真理永远用一般现在时，不受主句时态影响：He said the earth goes round the sun.','主句为过去时，从句时态变化：一般现在→一般过去；现在进行→过去进行；现在完成→过去完成；一般将来→过去将来'],'examples':['He said he would come the next day.','She told me she had finished her work.'],'common_mistakes':['主句过去时，从句用现在时（客观真理除外）']},

    # ============ 状语从句 ============
    'adv-time':{'rules':['时间状语从句的时态：主将从现','when/while/as 的区别：when 广泛使用；while 加持续动作；as 加短暂动作或表示"随着"','as soon as/the moment/the minute = 一...就','until/till：肯定句（持续到...为止）；not...until（直到...才）','since：主句用现在完成时，从句用一般过去时','before/after：before 从句用一般现在时表将来；after 从句可用现在完成时强调动作完成'],'examples':['I will call you as soon as I arrive.','He didn\'t go to bed until his mother came back.'],'common_mistakes':['When he will come → When he comes','until 和 not...until 混淆']},
    'adv-condition':{'rules':['条件状语从句：主将从现——主句用将来时，if/unless 从句用一般现在时','if = 如果：If it rains, we will stay home.','unless = if...not = 除非/如果不：You will fail unless you study hard.','as long as/so long as = 只要','in case = 以防/万一','on condition that/provided that = 条件是'],'examples':['If you work hard, you will succeed.','I won\'t go unless I am invited.'],'common_mistakes':['If it will rain → If it rains','unless 误用为 if']},
    'adv-concession':{'rules':['让步状语从句：although/though（虽然）, even though/even if（即使）, while/whereas（虽然/然而）, no matter + wh-（无论）','关键规则：although/though 不能与 but 同时使用','as/though 倒装：Child as he is, he knows a lot.','whether...or = 无论...还是'],'examples':['Although he is old, he is very active.','No matter what happens, I will support you.'],'common_mistakes':['Although...but 连用','no matter what 与 whatever 的用法区别']},
    'adv-cause':{'rules':['原因状语从句：because（因为，语气最强，回答 why）, since（既然）, as（由于）, for（因为，并列连词）','because 和 so 不能同时使用','because of + 名词、due to + 名词、thanks to + 名词、owing to + 名词','now that = 既然'],'examples':['He was late because he missed the bus.','Since everyone is here, let\'s begin.'],'common_mistakes':['because...so 连用','because 和 because of 混淆']},
    'adv-purpose-result':{'rules':['目的状语从句：so that/in order that + 从句（从句常用 can/could/may/might）','结果状语从句：so...that/such...that = 如此...以至于','so + adj/adv + that；such + (a/an) + adj + n + that','so that 既可表目的也可表结果','in order to/so as to + 动词原形（简单句中的目的状语）'],'examples':['He got up early so that he could catch the first bus.','It is such a good book that I have read it three times.'],'common_mistakes':['so...that 和 such...that 混淆','so as to 的否定：so as not to']},

    # ============ 定语从句 ============
    'attr-relative-pronouns':{'rules':['关系代词引导定语从句：who(人/主), whom(人/宾), which(物), that(通用), whose(所属)','who/whom/which 可用 that 替换（在限制性定语从句中）','关系代词在从句中作宾语时可以省略：The man (who/that) I saw was Tom.','介词 + which/whom：The house in which he lives is old.','只用 that 不用 which 的情况：①先行词为不定代词(all, much, little等)；②先行词有最高级/序数词修饰；③先行词有人又有物'],'examples':['The man who is talking to Mary is my uncle.','This is the best film that I have ever seen.'],'common_mistakes':['who 和 whom 混淆','that 用于非限制性定语从句']},
    'attr-that-special':{'rules':['必须用 that 的情况：①先行词为 all, everything, nothing, something, anything, little, much 等不定代词；②先行词被序数词或最高级修饰；③先行词被 the only, the very, the same, the last 修饰；④先行词既有人又有物；⑤主句以 who/which 开头的疑问句','不能用 that 的情况：①非限制性定语从句（that 只能用于限制性定语从句）；②介词后（介词+which/whom，不用 that）'],'examples':['All that glitters is not gold.','He is the only person that can help you.'],'common_mistakes':['在非限制性定语从句中用 that','介词后用 that']},
    'attr-relative-adverbs':{'rules':['关系副词引导定语从句：when(时间), where(地点), why(原因)','when 的先行词：time, day, year, moment 等','where 的先行词：place, house, city, country, school 等','why 的先行词：reason','关系副词 = 介词 + which：when = at/in/on which; where = at/in which; why = for which'],'examples':['I will never forget the day when I met her.','This is the reason why I was late.'],'common_mistakes':['关系副词和关系代词混淆','when 和 that 混用']},
    'attr-restrictive':{'rules':['限制性定语从句：对先行词起限定作用，不可省略，不用逗号隔开','非限制性定语从句：对先行词起补充说明作用，可省略，用逗号隔开，用 which/who，不用 that','as 引导的定语从句：as is known to all, as we all know','"介词+关系代词" 结构：in which, for which, of whom'],'examples':['He has two sons who are doctors.（可能还有别的儿子——限制性）','He has two sons, who are doctors.（只有两个儿子——非限制性）'],'common_mistakes':['非限制性定语从句用 that']},

    # ============ 虚拟语气 ============
    'subj-if':{'rules':['if 条件句的虚拟语气：与现在事实相反→If I were you, I would go.；与过去事实相反→If I had known, I would have told you.；与将来事实相反→If it were to rain, we would stay home.','错综时间条件句：If you had followed my advice, you would be fine now.','含蓄条件句：without/but for/otherwise','if only = 要是...就好了（虚拟语气）','as if/as though + 虚拟语气'],'examples':['If I were you, I would accept the offer.','If he had come earlier, he would have met her.'],'common_mistakes':['If I was you → If I were you','时间混乱：主从句时态不匹配']},
    'subj-noun-clause':{'rules':['名词性从句中的虚拟语气：suggest, order, demand, propose, insist, recommend, require, request + that + (should) + 动词原形','It is necessary/important/strange that + (should) do','wish + 过去时（对现在虚拟）/ 过去完成时（对过去虚拟）/ would do（对将来愿望）','would rather + 过去时（对现在/将来虚拟）/ 过去完成时（对过去虚拟）','It is (high) time that + 过去时 = 该是做...的时候了'],'examples':['I suggest that he (should) go there at once.','I wish I had listened to your advice.'],'common_mistakes':['suggest 后不用虚拟语气','wish 后的时态用错']},
    'subj-other':{'rules':['It is (high/about) time that + 过去时/should do','would rather + sb + 过去时','as if/as though + 虚拟语气','if only + 虚拟语气','lest/for fear that + (should) do','含蓄条件：without/but for/or/otherwise'],'examples':['It is high time that we went to bed.','I would rather you came tomorrow.'],'common_mistakes':['It is time that + 现在时']},

    # ============ 语言交际 ============
    'comm-greeting':{'rules':['问候：How do you do?（初次见面，回答也是 How do you do?）','How are you?（熟人问候，回答 Fine, thank you.）','Nice to meet you.（回答 Nice to meet you, too.）','Good morning/afternoon/evening!','How is everything going?'],'examples':['— How do you do? — How do you do?','— Nice to meet you. — Nice to meet you, too.'],'common_mistakes':['How do you do? 回答 I\'m fine.→ How do you do?（初次见面固定回答）']},
    'comm-request':{'rules':['请求允许：Can/Could/May I...?；Would/Do you mind if I...?','请求帮助：Can/Could/Would you...?；Would you mind doing...?','回答允许：Sure./Of course./Certainly./Go ahead.','回答拒绝：Sorry, I\'m afraid not./I\'d love to, but...','Would you mind...? 回答：不介意→Not at all./Of course not.；介意→Sorry./I\'m afraid...'],'examples':['— Would you mind opening the window? — Not at all.','— May I use your phone? — Sure. Go ahead.'],'common_mistakes':['Would you mind...? 回答 Yes 表示介意（错）','Can/Could/May 在正式程度上的区别']},
    'comm-invitation':{'rules':['发出邀请：Would you like to...? / I\'d like to invite you to...','接受邀请：Yes, I\'d love to./That sounds great./It\'s very kind of you.','拒绝邀请：I\'d love to, but.../Sorry, I\'m afraid I can\'t.','Would you like some...? 肯定回答→Yes, please.；否定→No, thanks.'],'examples':['— Would you like to join us? — I\'d love to.','— Shall we go swimming? — Good idea!'],'common_mistakes':['Would you like...? 回答 Yes, I like → Yes, I\'d love to']},
    'comm-agreement':{'rules':['表示同意：I agree with you./I think so, too./That\'s right./Exactly.','表示不同意：I don\'t think so./I\'m afraid I disagree./I\'m afraid you\'re wrong.','So do I./Neither do I. 的用法：So+助动词+主语=...也一样；Neither/Nor+助动词+主语=...也不'],'examples':['— I like music. — So do I.','— I can\'t swim. — Neither can I.'],'common_mistakes':['So do I 和 So I do 混淆','Neither 后用错助动词']},
    'comm-situational':{'rules':['感谢：Thank you./Thanks a lot. 回答：You\'re welcome./My pleasure./Not at all./Don\'t mention it.','道歉：I\'m sorry./Excuse me. 回答：That\'s all right./Never mind./It doesn\'t matter.','祝愿：Good luck!/Have a nice day! 回答：Thank you./The same to you.','打电话：Hello, this is...speaking./May I speak to...?/Hold on, please.','购物：Can I help you?/What can I do for you?/How much is it?','问路：Excuse me, where is...?/How can I get to...?','看病：What\'s wrong with you?/I have a headache./Take this medicine.'],'examples':['— Thank you very much. — You\'re welcome.','— I\'m sorry I\'m late. — That\'s all right.'],'common_mistakes':['Thank you 回答用 No thanks（错）','Excuse me 和 I\'m sorry 混淆']},
}

# Apply
updated=0
for m in modules['modules']:
    for s in m['sub_modules']:
        sid=s['id']
        if sid in G:
            s['grammar_summary']=G[sid]
            updated+=1

print(f"Updated: {updated} sub-modules")

with open(os.path.join(ROOT,'data','modules.json'),'w',encoding='utf-8') as f:
    json.dump(modules,f,ensure_ascii=False,indent=2)
import subprocess
subprocess.run(['python3',os.path.join(ROOT,'build.py')],capture_output=True)
print("Rebuilt!")
